In [1]:
import pandas as pd

In [2]:
import json

In [3]:
import requests

In [4]:
import datetime

In [5]:
import numpy as np

In [6]:
from fredapi import Fred

In [7]:
fred= Fred(api_key='04cd69bf4695c14ac7bce72969b5ae96')

In [8]:
BitcoinPrice = fred.get_series('CBBTCUSD')

In [9]:
EthereumPrice= fred.get_series('CBETHUSD')

In [10]:
LitecoinPrice= fred.get_series('CBLTCUSD')

In [11]:
BCHPrice= fred.get_series('CBBCHUSD')

# Introducing a time lag, by shifting the Bitcoin Price forward 1 period

In [12]:
BitcoinPrice= BitcoinPrice.shift(periods=1)

In [13]:
df= pd.concat([BitcoinPrice, EthereumPrice, LitecoinPrice,BCHPrice],axis=1)

In [14]:
df

0        1       2       3
2014-12-01       NaN      NaN     NaN     NaN
2014-12-02    370.00      NaN     NaN     NaN
2014-12-03    378.00      NaN     NaN     NaN
2014-12-04    378.00      NaN     NaN     NaN
2014-12-05    377.10      NaN     NaN     NaN
...              ...      ...     ...     ...
2021-04-18  60199.33  2250.23  275.59  977.91
2021-04-19  56351.20  2174.98  264.02  899.12
2021-04-20  55797.39  2340.30  261.38  945.66
2021-04-21  56514.90  2366.63  259.85  917.84
2021-04-22  53919.48  2400.67  252.78  853.02

[2335 rows x 4 columns]

In [15]:
df.columns=('Bitcoin Price','Ethereum Price','Litcoin Price','BCH Price')

In [16]:
df = df.fillna(method='ffill')

In [17]:
df=df.loc['2017-12-21':'2020-12-01']

In [18]:
pd.set_option('display.max_rows', None)

In [19]:
df['BitcoinReturns']= np.log(df['Bitcoin Price']/df['Bitcoin Price'].shift(1))

In [20]:
df['Ethereum Returns']= np.log(df['Ethereum Price']/df['Ethereum Price'].shift(1))

In [21]:
df['Litcoin Returns']= np.log(df['Litcoin Price']/df['Litcoin Price'].shift(1))

In [22]:
df['BCH Returns']= np.log(df['BCH Price']/df['BCH Price'].shift(1))

In [23]:
df

Bitcoin Price  Ethereum Price  Litcoin Price  BCH Price  \
2017-12-21       16496.89          796.98         311.00    3162.53   
2017-12-22       15758.80          682.11         267.79    2719.99   
2017-12-23       14210.57          732.80         293.03    3160.00   
2017-12-24       15075.89          697.04         278.81    2919.01   
2017-12-25       14221.94          740.50         273.52    2835.99   
2017-12-26       14171.98          755.07         280.14    2928.04   
2017-12-27       15790.88          739.99         264.40    2719.69   
2017-12-28       15367.08          719.50         251.18    2493.19   
2017-12-29       14450.01          748.89         245.79    2658.51   
2017-12-30       14565.05          710.58         216.04    2261.00   
2017-12-31       12839.99          741.27         227.17    2366.90   
2018-01-01       13863.13          759.03         225.22    2326.86   
2018-01-02       13480.01          865.00         253.31    2558.58   
2018-01-03       14781.51          938.31         244.99    2548.65   
2018-01-04       15098.14          949.00         238.91    2362.74   
2018-01-05       15144.99          969.27         246.23    2398.00   
2018-01-06       16960.01         1006.68         279.42    2524.72   
2018-01-07       17098.99         1118.30         272.06    2523.10   
2018-01-08       16174.22         1137.01         255.21    2409.29   
2018-01-09       14993.74         1290.01         246.89    2375.99   
2018-01-10       14480.99         1246.94         248.81    2859.97   
2018-01-11       14875.18         1137.01         226.91    2433.80   
2018-01-12       13308.06         1260.00         235.52    2599.00   
2018-01-13       13820.00         1386.02         258.00    2654.95   
2018-01-14       14187.95         1365.46         237.89    2544.87   
2018-01-15       13656.23         1278.63         232.51    2400.06   
2018-01-16       13590.00         1080.00         191.13    1890.01   
2018-01-17       11570.01         1028.06         189.00    1755.98   
2018-01-18       11200.01         1025.78         192.60    1730.67   
2018-01-19       11305.53         1037.45         192.50    1758.69   
2018-01-20       11498.99         1150.02         210.91    2030.22   
2018-01-21       12762.80         1047.13         191.25    1770.00   
2018-01-22       11518.17          999.68         179.42    1609.34   
2018-01-23       10766.70          984.03         178.27    1615.75   
2018-01-24       10824.94         1056.99         180.60    1644.50   
2018-01-25       11356.79         1040.00         178.86    1628.39   
2018-01-26       11118.00         1045.57         175.71    1592.14   
2018-01-27       11086.89         1100.00         179.65    1613.41   
2018-01-28       11319.00         1215.01         191.12    1719.99   
2018-01-29       11536.00         1162.27         179.57    1636.38   
2018-01-30       11123.01         1054.39         164.25    1446.00   
2018-01-31        9995.00         1105.01         161.90    1472.74   
2018-02-01       10099.99         1017.48         140.60    1254.86   
2018-02-02        9014.23          911.99         130.69    1181.00   
2018-02-03        8787.52          969.40         160.97    1269.71   
2018-02-04        9240.00          826.00         147.50    1156.16   
2018-02-05        8167.91          693.54         124.98     880.00   
2018-02-06        6905.19          783.83         141.50     968.01   
2018-02-07        7688.46          750.04         137.80     955.00   
2018-02-08        7575.75          812.00         149.00    1278.00   
2018-02-09        8218.10          875.99         164.10    1299.83   
2018-02-10        8671.01          849.47         155.08    1239.70   
2018-02-11        8547.49          811.35         149.26    1210.00   
2018-02-12        8072.99          864.40         161.50    1279.39   
2018-02-13        8872.28          840.49         158.91    1219.82   
2018-02-14        8520.01          9

In [24]:
df = df.drop(df.index[0])

In [25]:
df

Bitcoin Price  Ethereum Price  Litcoin Price  BCH Price  \
2017-12-22       15758.80          682.11         267.79    2719.99   
2017-12-23       14210.57          732.80         293.03    3160.00   
2017-12-24       15075.89          697.04         278.81    2919.01   
2017-12-25       14221.94          740.50         273.52    2835.99   
2017-12-26       14171.98          755.07         280.14    2928.04   
2017-12-27       15790.88          739.99         264.40    2719.69   
2017-12-28       15367.08          719.50         251.18    2493.19   
2017-12-29       14450.01          748.89         245.79    2658.51   
2017-12-30       14565.05          710.58         216.04    2261.00   
2017-12-31       12839.99          741.27         227.17    2366.90   
2018-01-01       13863.13          759.03         225.22    2326.86   
2018-01-02       13480.01          865.00         253.31    2558.58   
2018-01-03       14781.51          938.31         244.99    2548.65   
2018-01-04       15098.14          949.00         238.91    2362.74   
2018-01-05       15144.99          969.27         246.23    2398.00   
2018-01-06       16960.01         1006.68         279.42    2524.72   
2018-01-07       17098.99         1118.30         272.06    2523.10   
2018-01-08       16174.22         1137.01         255.21    2409.29   
2018-01-09       14993.74         1290.01         246.89    2375.99   
2018-01-10       14480.99         1246.94         248.81    2859.97   
2018-01-11       14875.18         1137.01         226.91    2433.80   
2018-01-12       13308.06         1260.00         235.52    2599.00   
2018-01-13       13820.00         1386.02         258.00    2654.95   
2018-01-14       14187.95         1365.46         237.89    2544.87   
2018-01-15       13656.23         1278.63         232.51    2400.06   
2018-01-16       13590.00         1080.00         191.13    1890.01   
2018-01-17       11570.01         1028.06         189.00    1755.98   
2018-01-18       11200.01         1025.78         192.60    1730.67   
2018-01-19       11305.53         1037.45         192.50    1758.69   
2018-01-20       11498.99         1150.02         210.91    2030.22   
2018-01-21       12762.80         1047.13         191.25    1770.00   
2018-01-22       11518.17          999.68         179.42    1609.34   
2018-01-23       10766.70          984.03         178.27    1615.75   
2018-01-24       10824.94         1056.99         180.60    1644.50   
2018-01-25       11356.79         1040.00         178.86    1628.39   
2018-01-26       11118.00         1045.57         175.71    1592.14   
2018-01-27       11086.89         1100.00         179.65    1613.41   
2018-01-28       11319.00         1215.01         191.12    1719.99   
2018-01-29       11536.00         1162.27         179.57    1636.38   
2018-01-30       11123.01         1054.39         164.25    1446.00   
2018-01-31        9995.00         1105.01         161.90    1472.74   
2018-02-01       10099.99         1017.48         140.60    1254.86   
2018-02-02        9014.23          911.99         130.69    1181.00   
2018-02-03        8787.52          969.40         160.97    1269.71   
2018-02-04        9240.00          826.00         147.50    1156.16   
2018-02-05        8167.91          693.54         124.98     880.00   
2018-02-06        6905.19          783.83         141.50     968.01   
2018-02-07        7688.46          750.04         137.80     955.00   
2018-02-08        7575.75          812.00         149.00    1278.00   
2018-02-09        8218.10          875.99         164.10    1299.83   
2018-02-10        8671.01          849.47         155.08    1239.70   
2018-02-11        8547.49          811.35         149.26    1210.00   
2018-02-12        8072.99          864.40         161.50    1279.39   
2018-02-13        8872.28          840.49         158.91    1219.82   
2018-02-14        8520.01          920.26         211.85    1355.00   
2018-02-15        9472.98          9

In [57]:
y= df['BitcoinReturns']

In [58]:
X=df['Ethereum Returns']

In [28]:
x2= df['Litcoin Returns']

In [29]:
x3= df['BCH Returns']

In [30]:
y = (y - np.mean(y))/(np.std(y))

In [31]:
X = (X - np.mean(X))/(np.std(X))

In [32]:
x2 = (x2 - np.mean(x2))/(np.std(x2))

In [33]:
x3 = (x3 - np.mean(x3))/(np.std(x3))

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
data= [y,X,x2,x3]

In [36]:
scaler = StandardScaler()

In [37]:
print(scaler.fit(data))

StandardScaler()


In [38]:
print(scaler.mean_)

[-2.28591124  0.73295646 -0.4061244  ...  1.12596188  1.34984253
 -0.30422466]


In [ ]:
data= (scaler.transform(data))

In [41]:
data

array([[ 1.62869351e+00, -1.70249511e+00,  1.72357130e+00, ...,
        -7.88074610e-01, -1.41470388e+00,  1.67777931e+00],
       [-9.11975586e-01,  3.32604980e-01, -5.06130492e-01, ...,
         6.73774355e-01, -3.88195046e-01, -5.18703382e-01],
       [-7.18091974e-01,  5.22795674e-01, -4.82124935e-01, ...,
         1.26513073e+00,  1.23513739e+00, -2.30056305e-01],
       [ 1.37404809e-03,  8.47094455e-01, -7.35315875e-01, ...,
        -1.15083047e+00,  5.67761538e-01, -9.29019628e-01]])

# Might try to do it to the individual variables opposed to all together

In [59]:
y= y.values.reshape(-1,1)

In [60]:
X= X.values.reshape(-1,1)

In [61]:
x2= x2.values.reshape(-1,1)

In [62]:
x3 = x3.values.reshape(-1,1)

In [67]:
data= [y,X,x2,x3]

In [68]:
scaler = StandardScaler()

In [72]:
print(scaler.fit(X))

StandardScaler()


In [73]:
print(scaler.mean_)

[-0.00028727]


In [75]:
X= (scaler.transform(X))

In [76]:
X

array([[-2.94520814],
       [ 1.36441726],
       [-0.94304117],
       ...,
       [ 1.42793102],
       [ 1.16994443],
       [-0.9822792 ]])

In [77]:
y= (scaler.transform(y))

In [79]:
x2= (scaler.transform(x2))

In [80]:
x3= (scaler.transform(x3))

# L1 Regularisation (Lasso)

In [81]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [90]:
X_train

array([[-1.89690627e-02],
       [ 2.66246796e-02],
       [ 1.13743134e-01],
       [-8.84220540e-01],
       [ 1.44208386e+00],
       [ 1.86975803e-01],
       [-4.09170097e-01],
       [-1.40663882e-01],
       [-4.93464546e-01],
       [-3.35336561e-01],
       [ 8.07070073e-01],
       [-2.49262716e-01],
       [ 8.84415728e-02],
       [-4.70951687e-02],
       [-1.61870865e-01],
       [-2.44401047e-01],
       [-2.01117683e-01],
       [-3.58861145e-01],
       [-1.28724231e+00],
       [-1.71229278e+00],
       [ 5.59412938e-01],
       [-3.17465470e-01],
       [-1.46269127e-01],
       [-4.25630414e-01],
       [-1.73464871e-01],
       [-3.25691504e-01],
       [ 7.00145266e-02],
       [-3.46919647e-01],
       [ 3.34937471e-01],
       [-2.54577608e-02],
       [ 5.25666892e-01],
       [ 2.07979190e+00],
       [ 5.21662593e-01],
       [ 9.20404763e-02],
       [-1.52579127e+00],
       [-9.30607624e-02],
       [-4.17180237e-01],
       [ 7.64455281e-01],
       [-3.1

In [91]:
y_train

array([[-1.22289976e-01],
       [ 1.04261294e+00],
       [ 1.95382749e-01],
       [ 1.09366276e-02],
       [ 6.19833034e-01],
       [ 2.75075655e-01],
       [ 4.36915015e-01],
       [-1.04106118e-01],
       [-2.10286063e-01],
       [ 7.54580163e-02],
       [-2.38445109e+00],
       [ 1.23020678e+00],
       [-1.52112276e-01],
       [-4.12058229e-01],
       [-8.35963395e-01],
       [ 4.51051691e-01],
       [ 2.12045871e-01],
       [ 9.97559866e-01],
       [ 7.97876917e-01],
       [ 4.06915269e-01],
       [-3.41729878e-01],
       [-3.21915303e-01],
       [ 1.07082796e+00],
       [-1.98977593e-01],
       [ 7.30127258e-02],
       [ 6.32677088e-01],
       [-5.41835451e-01],
       [-1.63877521e+00],
       [-1.01542465e-01],
       [ 2.79530102e-01],
       [ 3.82925070e-02],
       [-2.57142671e-01],
       [-3.92941603e-02],
       [ 2.30394582e-02],
       [-1.37475754e-01],
       [ 4.14095711e-02],
       [ 1.10974603e-01],
       [-1.16110857e+00],
       [ 2.2

In [92]:
from sklearn.linear_model import LinearRegression
reg= LinearRegression().fit(X_train,y_train)

In [93]:
reg.score(X_test,y_test)

0.018455051374539955

In [94]:
reg.score(X_train,y_train)

0.014835989332836919

In [96]:
from sklearn import linear_model

lasso_reg= linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)

lasso_reg.fit(X_train,y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [97]:
lasso_reg.score(X_test, y_test)

-0.0006204501358493264

In [98]:
lasso_reg.score(X_train,y_train)

0.0

# L2 Regulisation (Ridge)

In [99]:
from sklearn.linear_model import Ridge

In [100]:
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)

In [102]:
ridge_reg.fit(X_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [103]:
ridge_reg.score(X_test,y_test)

0.018328480165281102

In [104]:
ridge_reg.score(X_train,y_train)

0.014761654899778098